import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import CardComponent from '../components/cards'
import SidebarComponent from '../components/sidebar'
import HeaderComponent from '../components/header'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>TaskTracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderComponent />
      <div className={styles.mid_container}>
        <SidebarComponent />
        <CardComponent />
      </div>
    </div>
  )
}

export default Home